version: "3.7"
services:
  postgres:
    image: "postgres:12.2"
    shm_size: 2gb
    ports:
      - "5490:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stacks_blockchain_api
      POSTGRES_PORT: 5432
    networks:
      - backend
  stacks-blockchain:
    image: blockstack/stacks-blockchain:2.05.0.1.0
    command: sh -c "/wait && stacks-node start --config=/app/config/Stacks.toml"
    environment:
      WAIT_BEFORE: 3
      WAIT_AFTER: 3
      WAIT_HOSTS: "stacks-blockchain-api:3700"
      NOP_BLOCKSTACK_DEBUG: 1
      STACKS_EVENT_OBSERVER: stacks-blockchain-api:3700
      XBLOCKSTACK_DEBUG: 1
      RUST_BACKTRACE: 1
      STACKS_CHAIN_ID: "0x80000000"
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: postgres
      V2_POX_MIN_AMOUNT_USTX: 90000000260
      STACKS_CORE_RPC_HOST: stacks-blockchain
      STACKS_CORE_RPC_PORT: 20443
      STACKS_API_ENABLE_FT_METADATA: 1
      STACKS_API_ENABLE_NFT_METADATA: 1
    ports:
      - "20443:20443"
      - "20444:20444"
    volumes:
      - ./stacks-blockchain/config:/app/config
      - ./stacks-blockchain/chaindata:/tmp/stacks-blockchain-data
      - ./docker/wait:/wait
    networks:
      - backend
  stacks-blockchain-api:
    image: blockstack/stacks-blockchain-api:2.1.1
    restart: on-failure
    environment:
      WAIT_HOSTS: "postgres:5432"
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: stacks_blockchain_api
      STACKS_CORE_EVENT_PORT: "3700"
      STACKS_CORE_EVENT_HOST: http://0.0.0.0
      STACKS_BLOCKCHAIN_API_PORT: "3999"
      STACKS_BLOCKCHAIN_API_HOST: 0.0.0.0
      STACKS_BLOCKCHAIN_API_DB: pg
      STACKS_CORE_RPC_HOST: stacks-blockchain
      STACKS_CORE_RPC_PORT: "20443"
      STACKS_CHAIN_ID: "0x80000000"
      NODE_ENV: development
    ports:
      - "3999:3999"
      - "9153:9153"
    volumes:
      - ./docker/wait:/wait

    networks:
      - backend
    depends_on:
      - postgres
  stacks-blockchain-explorer:
    image: blockstack/explorer
    ports:
      - "3300:3000"
    extra_hosts:
      - "stacks-blockchain-explorer.localhost:127.0.0.1"
    environment:
      TESTNET_API_SERVER: http://gateway.docker.internal:3999
      NEXT_PUBLIC_TESTNET_API_SERVER: http://gateway.docker.internal:3999
      NEXT_PUBLIC_MAINNET_API_SERVER: http://gateway.docker.internal:3999
      NEXT_PUBLIC_REGTEST_API_SERVER: http://gateway.docker.internal:3999
      NEXT_PUBLIC_DEPLOYMENT_URL: http://127.0.0.1:3999
      NEXT_PUBLIC_MAINNET_ENABLED: "true"
      NODE_ENV: development
    networks:
      - backend
  transform:
    image: "us-central1-docker.pkg.dev/fifth-compiler-334213/alexgo/alex-stacks-loader:v20220125-068bbbf4"
    environment:
      PG_CONNECTION_STRING: "postgresql://postgres:postgres@postgres:5432/stacks_blockchain_api"
      WAIT_BEFORE: 3
      WAIT_AFTER: 3
      WAIT_HOSTS: "stacks-blockchain-api:3700"
    networks:
      - backend
    volumes:
      - ./docker/wait:/wait
    command: sh -c "/wait && node /srv/main.js"

networks:
  backend:
